### ISSUE TITLE
How to link own domain ssl with the container?

### ISSUE THREAD

**Issue by BobWs** [ckulka/baikal-docker#11]
Can you please point me in de right direction, I have installed you image on a synology nas docker variant. I configured a reverse proxy for my domain on the nas. This is working when using the browser to browse to the admin page. But when trying to at caldav to iOS/macOS calendar I get a warning that the ssl cert is self sign and not my own SSL. 

How can I link my own ssl cert to the container?

**Comment by ckulka** [comment]
Can you share your `docker-compose.yml`?

**Comment by ckulka** [comment]
Hi @BobWs, copying this over from #10 , given this is the more appropriate issue. Regarding the certificates, in addition to mounting folders, can you also mount files?

With regular docker-compose.yml files and docker run, it's possible to mount a file into the container under a different name, basically renaming it inside the container.

Based on https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.apache.yaml#L15, it should look something like this:

```
services:
  baikal:
    image: ckulka/baikal:apache
    volumes:
      - baikal:/var/www/baikal/Specific
      - volume1/docker/baikal/ssl/cert.pem:/etc/ssl/private/baikal.public.pem
      - volume1/docker/baikal/ssl/privkey.pem:/etc/ssl/private/baikal.private.pem
```

I'm not sure if Synology can do this, but could you please try to replace your volume mount for the SSL folder with two file mounts, one for each certificate file, using a different target name?
