### ISSUE TITLE
Baikal throwing errors after upgrade

### ISSUE THREAD

**Issue by AlexKalopsia** [ckulka/baikal-docker#183]
I pulled the latest image and recreated the container.
The UI asked me to perform the upgrade.
Now I can't reach Baikal anymore.

```
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Flake/Framework.php(265): Flake\Framework::initDb
Sqlite()
#1 /var/www/baikal/Core/Frameworks/Flake/Framework.php(205): Flake\Framework::initDb
()
#2 /var/www/baikal/html/dav.php(50): Flake\Framework::bootstrap()
#3 {main}
  thrown in /var/www/baikal/Core/Frameworks/Flake/Framework.php on line 269" while r
eading response header from upstream, client: 172.20.0.1, server: _, request: "PROPF
IND /dav.php/calendars/ala/default/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/ph
p-fpm.sock:", host: "dav.mydomain.com"
172.20.0.1 - alex [22/Apr/2024:20:26:19 +0000] "PROPFIND /dav.php/calendars/ala/defa
ult/ HTTP/1.1" 500 5 "-" "DAVx5/4.3.16.1-gplay (2024/04/17; dav4jvm; okhttp/4.12.0)
Android/12" "192.168.1.1"
2024/04/22 20:26:19 [error] 49#49: *8 FastCGI sent in stderr: "PHP message: PHP Warn
ing:  Trying to access array offset on value of type null in /var/www/baikal/Core/Fr
ameworks/Flake/Framework.php on line 262PHP message: PHP Warning:  Trying to access
array offset on value of type null in /var/www/baikal/Core/Frameworks/Flake/Framewor
k.php on line 262PHP message: PHP Fatal error:  Uncaught TypeError: Flake\Framework:
:initDbSqlite(): Argument #1 ($config) must be of type array, null given, called in
/var/www/baikal/Core/Frameworks/Flake/Framework.php on line 265 and defined in /var/
www/baikal/Core/Frameworks/Flake/Framework.php:269
```

Compose:

```
baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    restart: always
    ports:
      - "5233:80"
    volumes:
      - ${DOCKER_PATH}/baikal/config:/var/www/baikal/config
      - ${DOCKER_PATH}/baikal/data:/var/www/baikal/Specific
    depends_on:
      - mariadb
```
