### ISSUE TITLE
Can't get Baikal to work with Traefik v3

### ISSUE THREAD

**Issue by aftraid8** [ckulka/baikal-docker#264]
I'm trying to setup Baikal on my server with Traefik v3. It seems like the docs only is for v2.

With this setup I can reach Baikal on http://192.168.x.x:8082 and http://dav.my.domain:8082, but it's not available on https://dav.my.domain which I expect. I only get a "404 page not found" at that address.

When I visit either the IP address or the domain (without https) i get an entry in the Traefik logs saying:

```
2025/03/16 11:28:19 [error] 49#49: *1 FastCGI sent in stderr: "PHP message: Symfony\Component\Yaml\Exception\ParseException: File "/var/www/baikal/config/baikal.yaml" does not exist. in /var/www/baikal/vendor/symfony/yaml/Parser.php:55

Stack trace:
#0 /var/www/baikal/vendor/symfony/yaml/Yaml.php(57): Symfony\Component\Yaml\Parser->parseFile()
#1 /var/www/baikal/Core/Frameworks/Flake/Framework.php(210): Symfony\Component\Yaml\Yaml::parseFile()
#2 /var/www/baikal/Core/Frameworks/Flake/Framework.php(175): Flake\Framework::defineBaseUri()
#3 /var/www/baikal/html/admin/install/index.php(57): Flake\Framework::bootstrap()
#4 {main}PHP message: Error reading baikal.yaml file : File "/var/www/baikal/config/baikal.yaml" does not exist.PHP message: Error reading baikal.yaml file : File "/var/www/baikal/config/baikal.yaml" does not exist.PHP message: Error reading baikal.yaml file : File "/var/www/baikal/config/baikal.yaml" does not exist.PHP message: Error reading baikal.yaml file : File "/var/www/baikal/config/baikal.yaml" does not exist" while reading response header from upstream, client: 192.168.x.xx, server: _, request: "GET /admin/install/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dav.my.domain:8082"
192.168.x.xx - - [16/Mar/2025:11:28:19 +0000] "GET /admin/install/ HTTP/1.1" 200 18845 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.8.2 Chrome/122.0.6261.171 Safari/537.36" "-"
```

I've tried to run the compose.yml file with the `BAIKAL_SKIP_CHOWN` environment variable.
I've tried to manually set the permissions like it says in the top comments of [this file](https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.ssl.yaml)  and also tried not creating the dirs at all and let them be auto created and nothing seems to work. When not setting the permissions myself it defaults to "sshd crontab".

If I look inside of the container `/var/www/baikal/config/baikal.yaml` doesn't exist, only `.htaccess`. Everything in `/var/www` is owned by `nginx` user and group.

Here is my compose.yml contents:

```
services:
  baikal:
    image: ckulka/baikal:0.10.1-nginx
    container_name: baikal
    ports:
      - "8082:80" 
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"
      - "traefik.http.middlewares.baikal.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.baikal.redirectregex.replacement=https://$$1/dav.php/"
      - "traefik.http.middlewares.baikal.redirectregex.permanent=true"
      - "traefik.http.routers.baikal-https.rule=Host(`dav.my.domain`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.baikal-https.entrypoints=https"
      - "traefik.http.routers.baikal-https.tls=true"
      - "traefik.http.routers.baikal-https.service=baikal"
      - "traefik.http.routers.baikal-http.rule=Host(`dav.my.domain`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.baikal-http.entrypoints=http"
      - "traefik.http.routers.baikal-http.middlewares=redirect-https"
      - "traefik.http.routers.baikal-http.service=baikal"
      - "traefik.http.routers.baikal.middlewares=baikal"
        #      - "traefik.http.services.baikal.loadbalancer.server.port=8082"
      - "traefik.http.routers.baikal.tls.certresolver=acme"
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific
    networks:
      - proxy

networks:
  proxy:
    external: true
```

I'm not an expert either on Docker or Traefik and I don't know where I messed up. I hope I provided enough info, otherwise I'll be happy to provide more if needed. I do use more or less the same compose.yml-file as most of my other services which works fine.
