### ISSUE TITLE
Local mounts are not working

### ISSUE THREAD

**Issue by ghost** [ckulka/baikal-docker#272]
Using the docker-compose example with local mounts as a guide, I attempted to get Baikal using the locations specified in there:

```
version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/baikal/config:/var/www/baikal/config
      - /opt/baikal/Specific:/var/www/baikal/Specific
```

I created the /opt/baikal folders and gave them the appropriate permission. I also copied in backup copies of the sqlite.db and baikal.yaml. Then I started the container using `docker compose up.` with the above compose file. However it doesn't reload the data from the backup copies which suggests that it isn't using the /opt/baikal folder at all.

Are there any debugging options available so I can see what it is doing. Docker Desktop logs show no reference to the local mount but I can create users and calendars, which suggests that it is storing the data somewhere. But just not in the volume specified.
