### ISSUE TITLE
Lost all Baikal data when updating Raspbian

### ISSUE THREAD

**Issue by Miq1** [ckulka/baikal-docker#273]
**Baikal version**: 0.10.1

**Expected behaviour**:
The Baikal database should not be affected by a Debian (Raspbian) system update.

**Current behaviour**:
Everything seems to be lost, Baikal is greeting me with initial setup upon 'docker-compose up -d'

**Steps to reproduce**:
1. sudo apt update
2. sudo apt upgrade
3. sudo reboot
4. docker-compose up -d 

The docker-compose.yml file:
```
version: '3'

services:
  baikal:
    image: ckulka/baikal:latest
    container_name: baikal
    ports:
      - "82:80"
    volumes:
      - baikal-data:/var/www/html/Specific
    environment:
      BAIKAL_DAV_REALM: "MyBaikalServer"

volumes:
  baikal-data:
```

There is neither ``/var/www/baikal`` folder nor ``/var/www/html/Specific`` any more...

I have the calendar and contacts data still on my mobile phone and set the DAVx5 option to "manual sync only" to prevent further loss, but I would need advice on 
- how to restore the data
- how to prevent that happening again
