### ISSUE TITLE
Only when restarting container: "Plugin.php differs from the packaged version"

### ISSUE THREAD

**Issue by Krystof0** [ckulka/baikal-docker#277]
### Thank you for your great work! 
Because of the newly integrated hafix I installed the new **0.10.1+hafix** (apache) this week. It works perfectly until I stop and start the container:  

```
[Thu May 01 17:43:34.435303 2025] [mpm_prefork:notice] [pid 1:tid 1] AH00170: caught SIGWINCH, shutting down gracefully
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-apply-home-assistant-fix.sh
30-apply-home-assistant-fix.sh: info: Plugin.php differs from the packaged version
```

This error happens every time when I use `docker compose stop` - `docker compose start` (or `docker compose restart`)

Everything work great if I use `docker compose down` - `docker compose up` (before or after the error occured)

My configuration:

OpenMediaVault 7.7.6-1 on Pi4b/8 up to date

```
services:
  baikal:
    image: ckulka/baikal:apache
    container_name: baikalapache
    environment:
      - PUID=${APPUSER_PUID}
      - PGID=${APPUSER_PGID}
      - TZ=${TIME_ZONE_VALUE}
      - APPLY_HOME_ASSISTANT_FIX=true
      - BAIKAL_SERVERNAME=cfnas1.local
      - BAIKAL_SERVERALIAS=localhost
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
      - /etc/ssl/private/baikal:/etc/ssl/private
    restart: unless-stopped
```
