### ISSUE TITLE
Restart of baikal in portainer after it was shut down leads to connection problems

### ISSUE THREAD

**Issue by update-freak** [ckulka/baikal-docker#284]
I had the situation that on my Synology NAS all docker containers were shut down (maybe due to overload) and then due to `restart: always` the container was restarted. But then I recognised that I got connection errors in DAVx5 on my android device.
After deleting the docker container and creating a new one the problem is solved and I got the connection without an error.
I had this strange situation multiple times.

baikal version: 0.10.1+hafix

```
services:
  baikal:
    container_name: Baikal
	image: ckulka/baikal:nginx
    ports:
      - 49179:80
    volumes:
      - /volume1/docker/baikal/config:/var/www/baikal/config:rw
      - /volume1/docker/baikal/Specific:/var/www/baikal/Specific:rw
    environment:
      - APPLY_HOME_ASSISTANT_FIX=true
      - TZ=Europe/Berlin
    restart: always
```

my current workaround is to use this docker compose and delete the docker container and create a new one if this happens
```
services:
  baikal:
    container_name: Baikal
	image: ckulka/baikal:nginx
    ports:
      - 49179:80
    volumes:
      - /volume1/docker/baikal/config:/var/www/baikal/config:rw
      - /volume1/docker/baikal/Specific:/var/www/baikal/Specific:rw
    environment:
      - APPLY_HOME_ASSISTANT_FIX=true
      - TZ=Europe/Berlin
    restart: unless-stopped
```
