### ISSUE TITLE
TLS using Caddy

### ISSUE THREAD

**Issue by Lithimlin** [ckulka/baikal-docker#33]
Hey, I'm currently trying to figure out if it's possible to use [Caddy](https://caddyserver.com/) as a reverse proxy and to handle the secure connection and certificate from Let's Encrypt.

I already have Caddy running as part of a different project and find it a bit easier to use than Nginx, especially in regards to automatic certificates. I haven't worked with Traefik yet but could, of course, just use [this docker-compose file](https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.ssl.yaml) to handle the job.

As a full disclaimer: I'm fairly new to docker, caddy, and things like self-hosting, networking, reverse-proxies,...

**Comment by Lithimlin** [comment]
I've found the fault in my logic. Nevertheless, here's my Caddyfile and docker-compose for those interested:

Caddyfile:
```
my.domain.tld {
	header / {
		# Enable HTTP Strict Transport Security (HSTS)
		Strict-Transport-Security "max-age=31536000;"
		# Enable cross-site filter (XSS) and tell browser to block detected attacks
		X-XSS-Protection "1; mode=block"
		# Disallow the site to be rendered within a frame (clickjacking protection)
		X-Frame-Options "DENY"
		# Prevent search engines from indexing
		X-Robots-Tag "none"
	}

	reverse_proxy baikal:80
}
```

docker-compose:
```
version: '3.5'

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
     - 8080:80
     - 8443:443 
    volumes:
     - ~/Caddyfile:/etc/caddy/Caddyfile
     - ~/site:/srv
     - ~/volumes/caddy/data:/data
     - ~/volumes/caddy/config:/config
    environment:
     - ACME_AGREE='true'
     - TZ=<my-timezone>

  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    restart: always
    volumes:
     - ~/volumes/baikal/config:/var/www/baikal/config
     - ~/volumes/baikal/data:/var/www/baikal/Specific
```

However, I'm still getting an "Insufficient permissions on the configuration folders" error. Baikal seems to be missing write permissions to the `/Specific` und `/config` folders.
