### ISSUE TITLE
Local folder for Specific data

### ISSUE THREAD

**Issue by Lithimlin** [ckulka/baikal-docker#39]
In my docker compose I'm trying to specify a local directory to mount into the container's `Specific` directory so I can backup it more easily. However, it does not work. Instead, docker creates a volume for me.

Here's my docker-compose:
```
  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    restart: always
    volumes:
     - ./volumes/baikal/config:/var/www/baikal/config
     - ./volumes/baikal/data:/var/www/baikal/Specific
```
Mounting the `config` directory works just fine.
Has anyone encountered a similar issue?
