### ISSUE TITLE
Exposing local directories for all directories within /var/www/baikal/

### ISSUE THREAD

**Issue by Sloshy1** [ckulka/baikal-docker#45]
As the title says, I've tried mapping ./www to /var/www and creaeting all the directories manually, and applying the same permissions that are in the example docker-compose.yml file to all the folders, but when I spin the container up it doesn't work. 

The reason I need to do this is I need to edit the .htaaccess file (for remapping the default iPhone CardDAV value) within the html directory, but my container doesn't have vim, vi, nano, or any other text editor installed, installing them is on face value a PITA, and I would much rather map everything to a local directory for future config changes if required.

**Comment by ckulka** [comment]
Hi @Sloshy1, just to make sure I understand your scenario correctly: you only need to modify the `/var/www/baikal/html/.htaccess` file?

I would recommend mounting just that modified file into the container and not the entire `/var/www/baikal` folder, for example based on [examples/docker-compose.localvolumes.yaml](https://github.com/ckulka/baikal-docker/blob/8781617f179fb7b115a179d47f425c460996c876/examples/docker-compose.localvolumes.yaml):

```yaml
version: '2'
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific
      # Mount your modified .htaccess file
      - ./my.htaccess:/var/www/baikal/html/.htaccess
```

My main reason is that you then don't have to worry about all the other files in the `/var/www/baikal` folder, especially when later upgrading to a newer version.

If you really (for other reasons) want to mount everything of `/var/www/baikal` from a local directory, you'll have to

1. Copy the Baikal files from the Docker image into your local directory
2. Fix file permissions
3. Add the mount in the Docker Compose file

```bash
# Step 1: create the local directory and get the Baikal files
mkdir /my/local/directory
docker run --rm -it -v /my/local/directory:/tmp ckulka/baikal cp -R /var/www/baikal /tmp

# Step 2: fix file permissions (Nginx)
chown -R 101:101 /my/local/directory

# Step 2: fix file permissions (Apache)
chown -R 33:33 /my/local/directory
```

Let me know if that helps 👍
